### ISSUE TITLE
App build without issues but fails at execution

### ISSUE THREAD

**Issue by praduca** [thma/ThreepennyElectron#4]
Following the instructions to build, the app fails at runtime with an javascript error (it opens on a graphhcal window so cant copy the error here) and show a blank window when executing. The error says "image could not be created from calc.ico"

Commenting out the offending line (main.js line 49  ) apparently solves the issue, but even if you dont change this line, calling the app adress from the browser shows the calculator just fine... So I suspect that is some that changed with electron, or with the threepennygui lib  (dont know how to debug this myself).

**Comment by thma** [comment]
Hi Flavio, 
Are you working on Mac, Linux or Windows?

If the app is working fine in the browser that means 
1. The Haskell code + ThreePenny work fine !
2. that the problem is in Electron. 

Which version of electron are you using?

My last commit to the project is two years old. So I think that many things in Electron (and maybe also in some NPM libraries) have changed quite a bit...

**Comment by thma** [comment]
I just have updated the versions of electron and all supporting npm libraries to their latest versions.
And a small fix to main.js

npm install
npm start

now works perfectly again on my machine

**Comment by praduca** [comment]
hi sorry for the delay on the answer
I will test this tonight
I'm using wsl and will also try on windows and Nixos linux asasp

**Comment by praduca** [comment]
It worked perfectly now, tks!
I tested on wsl and windows,. I will test on nixos but I don't see any reason for this not work there
tks again!

**Comment by thma** [comment]
Great news !
